name: Deploy to Firebase Hosting on commit
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
          with:
            node-version: '10.x'
        - run: cd public
        - run: npm install
        - run: npm run prod
        - run: cd ..
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDEO_SYNCHRONIZE }}'
          channelId: live
          projectId: video-synchronize
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
